import type { DashboardConversation, DashboardSourceOption } from "@/modules/dashboard/types";

export const dashboardMockToday = "2026-04-01";

export const dashboardSourceOptions: DashboardSourceOption[] = [
  {
    id: "page-a",
    label: "Pancake / Nha khoa Q1",
    description: "Page chốt lịch và tư vấn tổng quát cho khu trung tâm."
  },
  {
    id: "page-b",
    label: "Facebook / Implant Hub",
    description: "Nguồn hội thoại từ campaign implant, bảng giá và trả góp."
  },
  {
    id: "page-c",
    label: "Instagram / Smile Studio",
    description: "Nguồn social cho thẩm mỹ, veneer và review dịch vụ."
  }
];

function createConversation(conversation: DashboardConversation) {
  return conversation;
}

export const dashboardConversations: DashboardConversation[] = [
  createConversation({
    id: "conv-a-0401-01",
    sourceId: "page-a",
    customerName: "Nguyen Minh Thu",
    staffName: "Linh",
    primaryNeed: "Đặt lịch",
    occurredAt: "2026-04-01T09:15:00+07:00",
    summary: "Khách cần lịch khám trong ngày và xác nhận khung giờ bác sĩ trống.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "won",
    warningCount: 0,
    aiCost: 0.031
  }),
  createConversation({
    id: "conv-a-0401-02",
    sourceId: "page-a",
    customerName: "Tran Gia Han",
    staffName: "Vy",
    primaryNeed: "Báo giá",
    occurredAt: "2026-04-01T10:05:00+07:00",
    summary: "Khách hỏi giá niềng răng và cần so sánh hai gói chi phí khác nhau.",
    inboxStatus: "existing",
    revisitStatus: "revisit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 1,
    aiCost: 0.029
  }),
  createConversation({
    id: "conv-a-0401-03",
    sourceId: "page-a",
    customerName: "Doan Bao Ngoc",
    staffName: "Linh",
    primaryNeed: "Tái khám",
    occurredAt: "2026-04-01T11:22:00+07:00",
    summary: "Khách muốn dời lịch tái khám và kiểm tra lại ghi chú từ buổi trước.",
    inboxStatus: "existing",
    revisitStatus: "revisit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.03
  }),
  createConversation({
    id: "conv-a-0401-04",
    sourceId: "page-a",
    customerName: "Mai Thanh Son",
    staffName: "Vy",
    primaryNeed: "Tư vấn dịch vụ",
    occurredAt: "2026-04-01T13:40:00+07:00",
    summary: "Khách mới muốn được tư vấn tổng quan về răng sứ và thời gian điều trị.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.025
  }),
  createConversation({
    id: "conv-a-0401-05",
    sourceId: "page-a",
    customerName: "Nguyen Quoc Bao",
    staffName: "Linh",
    primaryNeed: "Khiếu nại",
    occurredAt: "2026-04-01T15:10:00+07:00",
    summary: "Khách phản ánh việc chậm gọi lại sau tư vấn và yêu cầu phản hồi rõ ràng hơn.",
    inboxStatus: "existing",
    revisitStatus: "first_visit",
    sentiment: "negative",
    closingOutcome: "lost",
    warningCount: 2,
    aiCost: 0.038
  }),
  createConversation({
    id: "conv-a-0401-06",
    sourceId: "page-a",
    customerName: "Le Khanh Chi",
    staffName: "Vy",
    primaryNeed: "Đặt lịch",
    occurredAt: "2026-04-01T16:25:00+07:00",
    summary: "Khách mới hỏi lịch cuối tuần và muốn biết thủ tục trước khi đến khám.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "open",
    warningCount: 1,
    aiCost: 0.027
  }),
  createConversation({
    id: "conv-b-0401-01",
    sourceId: "page-b",
    customerName: "Le Hoang Nam",
    staffName: "An",
    primaryNeed: "Tái khám",
    occurredAt: "2026-04-01T09:48:00+07:00",
    summary: "Khách quay lại hỏi tiến độ implant và muốn xác nhận lịch tái khám.",
    inboxStatus: "existing",
    revisitStatus: "revisit",
    sentiment: "positive",
    closingOutcome: "won",
    warningCount: 0,
    aiCost: 0.034
  }),
  createConversation({
    id: "conv-b-0401-02",
    sourceId: "page-b",
    customerName: "Vo Thi Anh Dao",
    staffName: "Khai",
    primaryNeed: "Khiếu nại",
    occurredAt: "2026-04-01T12:05:00+07:00",
    summary: "Khách than phiền việc phản hồi chậm sau khi đã gửi bảng giá implant.",
    inboxStatus: "existing",
    revisitStatus: "first_visit",
    sentiment: "negative",
    closingOutcome: "lost",
    warningCount: 2,
    aiCost: 0.039
  }),
  createConversation({
    id: "conv-b-0401-03",
    sourceId: "page-b",
    customerName: "Ngo Tuan Kiet",
    staffName: "An",
    primaryNeed: "Báo giá",
    occurredAt: "2026-04-01T14:18:00+07:00",
    summary: "Khách cần bảng giá trọn gói implant và hỏi thêm về chính sách trả góp.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.033
  }),
  createConversation({
    id: "conv-c-0401-01",
    sourceId: "page-c",
    customerName: "Pham Nhat Vy",
    staffName: "Tram",
    primaryNeed: "Tư vấn dịch vụ",
    occurredAt: "2026-04-01T10:42:00+07:00",
    summary: "Khách mới hỏi dịch vụ veneer và cần xem lộ trình tư vấn phù hợp.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.028
  }),
  createConversation({
    id: "conv-c-0401-02",
    sourceId: "page-c",
    customerName: "Bui Quang Huy",
    staffName: "Trang",
    primaryNeed: "Đặt lịch",
    occurredAt: "2026-04-01T17:12:00+07:00",
    summary: "Khách muốn giữ lịch tẩy trắng cuối tuần và hỏi thời lượng thực hiện.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "won",
    warningCount: 0,
    aiCost: 0.026
  }),
  createConversation({
    id: "conv-a-0330-01",
    sourceId: "page-a",
    customerName: "Vu Ngoc Han",
    staffName: "Linh",
    primaryNeed: "Báo giá",
    occurredAt: "2026-03-30T14:05:00+07:00",
    summary: "Khách cần so sánh giá niềng mắc cài và niềng trong suốt.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.024
  }),
  createConversation({
    id: "conv-a-0328-01",
    sourceId: "page-a",
    customerName: "Tran Tuan Duy",
    staffName: "Vy",
    primaryNeed: "Đặt lịch",
    occurredAt: "2026-03-28T11:18:00+07:00",
    summary: "Khách muốn đặt lịch khám ngoài giờ hành chính và xác nhận phí ban đầu.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "won",
    warningCount: 0,
    aiCost: 0.021
  }),
  createConversation({
    id: "conv-a-0315-01",
    sourceId: "page-a",
    customerName: "Hoang My Linh",
    staffName: "Linh",
    primaryNeed: "Tư vấn dịch vụ",
    occurredAt: "2026-03-15T16:40:00+07:00",
    summary: "Khách hỏi dịch vụ bọc sứ và cần đánh giá trước khi lên lịch khám.",
    inboxStatus: "existing",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "open",
    warningCount: 1,
    aiCost: 0.026
  }),
  createConversation({
    id: "conv-b-0311-01",
    sourceId: "page-b",
    customerName: "Trinh Nhat Quang",
    staffName: "An",
    primaryNeed: "Báo giá",
    occurredAt: "2026-03-11T10:10:00+07:00",
    summary: "Khách đang cân đối hai phương án implant sau khi nhận báo giá chi tiết.",
    inboxStatus: "existing",
    revisitStatus: "first_visit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.035
  }),
  createConversation({
    id: "conv-c-0303-01",
    sourceId: "page-c",
    customerName: "Ly My Duyen",
    staffName: "Tram",
    primaryNeed: "Tư vấn dịch vụ",
    occurredAt: "2026-03-03T15:36:00+07:00",
    summary: "Khách muốn tư vấn veneer và lịch phù hợp cho cuối tuần tới.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.024
  }),
  createConversation({
    id: "conv-a-0215-01",
    sourceId: "page-a",
    customerName: "Pham Gia Bao",
    staffName: "Vy",
    primaryNeed: "Tái khám",
    occurredAt: "2026-02-15T09:55:00+07:00",
    summary: "Khách hỏi kiểm tra lại sau điều trị và cần dời lịch tái khám sớm hơn.",
    inboxStatus: "existing",
    revisitStatus: "revisit",
    sentiment: "positive",
    closingOutcome: "won",
    warningCount: 0,
    aiCost: 0.022
  }),
  createConversation({
    id: "conv-b-0112-01",
    sourceId: "page-b",
    customerName: "Nguyen Dinh Khanh",
    staffName: "Khai",
    primaryNeed: "Khiếu nại",
    occurredAt: "2026-01-12T13:30:00+07:00",
    summary: "Khách chưa hài lòng vì lịch hẹn bị thay đổi nhiều lần mà không báo sớm.",
    inboxStatus: "existing",
    revisitStatus: "first_visit",
    sentiment: "negative",
    closingOutcome: "lost",
    warningCount: 3,
    aiCost: 0.041
  }),
  createConversation({
    id: "conv-c-1218-01",
    sourceId: "page-c",
    customerName: "Vo Thao My",
    staffName: "Trang",
    primaryNeed: "Đặt lịch",
    occurredAt: "2025-12-18T11:00:00+07:00",
    summary: "Khách đặt lịch tư vấn thẩm mỹ răng và muốn giữ ca buổi tối.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "won",
    warningCount: 0,
    aiCost: 0.023
  }),
  createConversation({
    id: "conv-a-1009-01",
    sourceId: "page-a",
    customerName: "Nguyen Thu Phuong",
    staffName: "Linh",
    primaryNeed: "Báo giá",
    occurredAt: "2025-10-09T08:45:00+07:00",
    summary: "Khách hỏi giá trọn gói chỉnh nha và timeline thanh toán dự kiến.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.02
  }),
  createConversation({
    id: "conv-b-0722-01",
    sourceId: "page-b",
    customerName: "Do Duc Minh",
    staffName: "An",
    primaryNeed: "Tư vấn dịch vụ",
    occurredAt: "2025-07-22T16:05:00+07:00",
    summary: "Khách muốn hiểu quy trình implant trước khi quyết định đặt lịch tư vấn.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "positive",
    closingOutcome: "open",
    warningCount: 0,
    aiCost: 0.019
  }),
  createConversation({
    id: "conv-c-0505-01",
    sourceId: "page-c",
    customerName: "Ha Gia Linh",
    staffName: "Tram",
    primaryNeed: "Báo giá",
    occurredAt: "2025-05-05T12:12:00+07:00",
    summary: "Khách cần báo giá veneer và hỏi thời gian hoàn thiện trước sự kiện.",
    inboxStatus: "new",
    revisitStatus: "first_visit",
    sentiment: "neutral",
    closingOutcome: "open",
    warningCount: 1,
    aiCost: 0.021
  })
];
