export const permissionCodes = {
  GET_AUTH_ME: "GET_AUTH_ME",
  REFRESH_AUTH_SESSION: "REFRESH_AUTH_SESSION",
  LOGOUT_AUTH_SESSION: "LOGOUT_AUTH_SESSION",
  CHANGE_OWN_PASSWORD: "CHANGE_OWN_PASSWORD",
  GET_USERS: "GET_USERS",
  GET_USER: "GET_USER",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  RESET_USER_PASSWORD: "RESET_USER_PASSWORD",
  DISABLE_USER: "DISABLE_USER",
  GET_ROLES: "GET_ROLES",
  ASSIGN_ROLE: "ASSIGN_ROLE",
  GET_PERMISSIONS: "GET_PERMISSIONS",
  GET_AUDIT_LOGS: "GET_AUDIT_LOGS",
  GET_DASHBOARD: "GET_DASHBOARD",
  EXPORT_REPORT: "EXPORT_REPORT"
} as const;

export type PermissionCode = (typeof permissionCodes)[keyof typeof permissionCodes];
